### ISSUE TITLE
Release update.

### ISSUE THREAD

**Issue by Pretmaker** [Spoffy/EcoDiscordPlugin#13] opened 2018-03-29 16:29 UTC
Hello, 

ECO just updated to 7.3.0 on pingperfect hosting which has an option to include this mod. It uses the released version to install, so the latest version is still 1.1.1 but you've changed your code a bit so I presume this error I get is fixed with the new releases that are in the code, but not in the releases yet.

Could you perhaps build a new release?

Error I'm getting with any commands ingame:
Method not found: 'Void Eco.Gameplay.Systems.Chat.ChatManager.ServerMessageToPlayer(System.String, Eco.Gameplay.Players.User, Boolean, Eco.Shared.Services.DefaultChatTags, Eco.Shared.Services.ChatCategory)'.

Stack:
   at Eco.Plugins.DiscordLink.DiscordEcoCommands.CallWithErrorHandling[TRet](EcoCommandFunction toCall, User user, String[] args)
   at Eco.Plugins.DiscordLink.DiscordEcoCommands.DiscordGuilds(User user)

**Comment by Spoffy** [comment] 2018-03-29 17:35
Hi Pret! Thanks for bringing this up! I'll make sure this is corrected and a new version released in the next few hours. I'll do an extra-thorough round of testing too. :)

**Comment by Spoffy** [comment] 2018-03-29 17:35
Additionally, thanks for the including the stack trace! It's super helpful, and has told me exactly what the problem is :)

**Comment by Spoffy** [comment] 2018-03-29 20:19
This is now fixed in 1.1.2-7.3.0, I'll be closing this, but feel free to comment if the issue persists!

**Closed by Spoffy** 2018-03-29 20:19 UTC
