### ISSUE TITLE
[2.0] ERROR: Error occurred while attempting to initialize the chat logger

### ISSUE THREAD

**Issue by TheKye** [Spoffy/EcoDiscordPlugin#58] opened 2020-08-18 17:26 UTC
`[08:33:58.632] [11] [ Info] [Eco] [DiscordLink] ERROR: Error occured while attempting to initialize the chat logger using path "C:\Users\admin\Desktop\Eco Server\Mods\DiscordLink\Chatlog.txt". Error message: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\Desktop\Eco Server\Mods\DiscordLink\Chatlog.txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Eco.Plugins.DiscordLink.DiscordLink.StartChatlog()
 `

**Comment by MonzUn** [comment] 2020-09-04 17:08
This was most likely caused by the DiscordLink directory not existing, as the release zip-files have the version number in them.

I've made a fix and it will be included in an upcoming release.

**Closed** 2020-09-04 17:09 UTC
Labels: bug, resolved
