### ISSUE TITLE
Multiple Server Support For a single Discord Guild

### ISSUE THREAD

**Issue by TheKye** [Spoffy/EcoDiscordPlugin#28] opened 2019-05-15 06:47 UTC
Is this a feature? or can we have this added
This will make it so users who have more then one server can keep them in the same discord

**Comment by Spoffy** [comment] 2019-05-15 17:47
Hi Kye - You should be able to set this up already. 
Install the bot on your two Eco servers using the same bot token.
Then link the various channels in your Discord server to the Eco game channels in each config file.

For example - link #EcoGeneralOne to #General on your first server, and #EcoGeneralTwo to #General on your second server.

Let me know if this resolves your problem or not!

**Comment by TheKye** [comment] 2019-05-16 03:43
i keep getting an error, ill put up the log for you,
i get this everytime i try to run the bot on the same discord when connecting to the server,

I Have tried with 2 sperarate bots as well as nothing but the bot token in the config file, it only works if i remove the config file but then the discord link doesn't operate
i am using ver 1.2.7
`Exception
Exception: WebException
Message:The remote server returned an error: (500) Internal Server Error.
Source:System

System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--END DUMP--`

**Comment by Spoffy** [comment] 2019-05-16 09:45
I'm not immediately sure what's causing that error, but I'm happy to look into it. Does this error happen without DiscordLink installed? And does it happen every single time?

**Comment by TheKye** [comment] 2019-05-16 09:53
every time discordlink  config file is loaded, doesn't come up without Discodlink installed,

**Comment by Spoffy** [comment] 2019-05-16 12:24
I'll look into it and get back to you with a solution as soon as possible!

**Comment by Spoffy** [comment] 2019-05-16 12:30
If you could post your config file with the token removed, that might help :)

**Comment by TheKye** [comment] 2019-05-16 12:31
[DiscordPluginSpoffy.zip](https://github.com/Spoffy/EcoDiscordPlugin/files/3187035/DiscordPluginSpoffy.zip)

**Comment by TheKye** [comment] 2019-05-16 12:32
the config file was generated by the GUI

**Comment by Spoffy** [comment] 2019-05-16 12:57
At what point does this error occur? When you start the Eco server running, and it's booting up? When you send a message in Eco?

**Comment by TheKye** [comment] 2019-05-16 13:00
After the server has booted up and a user trys to connect to the server sometimes before that

**Comment by Spoffy** [comment] 2019-05-16 13:05
Did you download your mod using Eco's built in Mod browser?

**Comment by TheKye** [comment] 2019-05-16 13:18
no i used mod.io then i used 1.2.7 from here

**Comment by Spoffy** [comment] 2019-05-16 13:22
I also just need to check - which version of Eco are you running?

**Comment by TheKye** [comment] 2019-05-16 13:24
8.1.4

**Comment by Spoffy** [comment] 2019-05-16 13:56
Try renaming ModKit.eco to ModKitOld.eco. That /might/ stop the problem. I'm not sure exactly what the cause is yet though, nor if that'll definitely work.

**Comment by Spoffy** [comment] 2019-05-16 13:56
That's in the Config folder

**Comment by Spoffy** [comment] 2019-05-16 14:21
Do you get the 'DiscordLink: Connected and Ready' message, or even just the 'Connected' message? Thanks for your patience - this is proving difficult to find. 

On 16 May 2019 14:24:07 BST, Kye <notifications@github.com> wrote:
>8.1.4
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/28#issuecomment-493065899

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TheKye** [comment] 2019-05-16 14:27
yeah i get the connected and ready message, ill try your idea now

**Comment by TheKye** [comment] 2019-05-16 14:34
Just tested your idea for changing modkit to modkitold and same issue

**Comment by Spoffy** [comment] 2019-05-16 15:09
The only other though I have at the moment is to try disabling user authentication (on a hunch) - I can't remember exactly which server tab that's in. 

I'll try to investigate in more detail tonight otherwise.

On 16 May 2019 15:34:24 BST, Kye <notifications@github.com> wrote:
>Just tested your idea for changing modkit to modkitold and same issue
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Spoffy/EcoDiscordPlugin/issues/28#issuecomment-493093643

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Spoffy** [comment] 2019-05-16 17:05
If you could also try adding DiscordLink to a clean install of Eco Server (download the server, add DiscordLink to the mods, add your config (or bot token as minimum)) and run it - I'd like to know if it's related to the way your server is set up, or if it's some part of your computer that's interacting with DiscordLink in a strange way.

**Comment by TheKye** [comment] 2019-05-16 17:06
i have tried it on 2 different servers on 2 different computers and the same result :/

**Comment by Spoffy** [comment] 2019-05-16 17:21
Are you running Windows or Linux? It's interesting you're having this 
issue - as it's the first time I've heard of it.

**Comment by TheKye** [comment] 2019-05-16 17:22
windows and linux

**Comment by Spoffy** [comment] 2019-05-16 17:23
Which version of Windows?

And did you try running it on a clean install of a server?

**Comment by TheKye** [comment] 2019-05-17 03:44
yeah it was a clean install and windows 10, and winders server 2016

**Comment by TheKye** [comment] 2019-05-17 03:45
ZLoveMonkey
#2566 add me on discord and ill talk to you there easier :)

**Comment by Spoffy** [comment] 2019-05-19 11:04
Caused by a mod conflict between this and TSO Vote Rewards in some situations. Resolved by re-ordering the mods, or removing one of them: results may vary.

**Closed by Spoffy** 2019-05-19 11:04 UTC
